apiVersion: builtin
kind: SecretGenerator
metadata:
  name: app-secret-env
literals:
  - MYSQL_USERNAME=admin
  - MYSQL_PASSWORD=password
envs:
  - secrets/secret.env
# options:
#   disableNameSuffixHash: true